import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service - ManlyDude',
  description: 'Terms of Service for the ManlyDude fitness platform.',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gradient-to-b from-gray-900 via-blue-950 to-gray-900 pt-24 text-white">
      <div className="mx-auto max-w-3xl px-6 py-16">
        <h1 className="mb-2 text-4xl font-black">Terms of Service</h1>
        <p className="mb-12 text-sm text-gray-500">Last updated: March 23, 2026</p>

        <div className="space-y-8 text-gray-300 [&_h2]:mb-3 [&_h2]:text-xl [&_h2]:font-bold [&_h2]:text-white [&_p]:leading-relaxed">
          <section>
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using ManlyDude (&quot;the Service&quot;), you agree to be bound by these
              Terms of Service. If you do not agree to these terms, do not use the Service. The
              Service is operated by NeuralQuantum.ai LLC through its VibeCaaS.com division.
            </p>
          </section>

          <section>
            <h2>2. Description of Service</h2>
            <p>
              ManlyDude is an AI-powered fitness and strength training platform that provides workout
              logging, AI-generated training plans, nutrition guidance, and coaching features. The
              Service is available via web and mobile applications.
            </p>
          </section>

          <section>
            <h2>3. User Accounts</h2>
            <p>
              You must create an account to use certain features of the Service. You are responsible
              for maintaining the confidentiality of your account credentials and for all activities
              that occur under your account. You must be at least 16 years of age to use the Service.
            </p>
          </section>

          <section>
            <h2>4. Subscription Plans &amp; Billing</h2>
            <p>
              ManlyDude offers free and paid subscription tiers (Plus at $19/month and Premium at
              $99/month). Paid subscriptions are billed monthly through Stripe. You may cancel your
              subscription at any time, and it will remain active until the end of the current billing
              period. Refunds are handled on a case-by-case basis.
            </p>
          </section>

          <section>
            <h2>5. AI-Generated Content</h2>
            <p>
              Workout plans, nutrition recommendations, and coaching advice generated by our AI
              (powered by Anthropic Claude) are for informational purposes only. They do not
              constitute medical, dietary, or professional fitness advice. Always consult a qualified
              healthcare professional before starting any new exercise or nutrition program.
            </p>
          </section>

          <section>
            <h2>6. User Content</h2>
            <p>
              You retain ownership of any content you submit to the Service (workout logs, progress
              photos, etc.). By submitting content, you grant ManlyDude a non-exclusive, worldwide
              license to use, store, and process that content for the purpose of providing the
              Service.
            </p>
          </section>

          <section>
            <h2>7. Acceptable Use</h2>
            <p>
              You agree not to misuse the Service, including but not limited to: reverse engineering
              the AI features, attempting to extract training data, using the Service for any unlawful
              purpose, or interfering with other users&apos; experience.
            </p>
          </section>

          <section>
            <h2>8. Limitation of Liability</h2>
            <p>
              ManlyDude and NeuralQuantum.ai LLC are not liable for any injuries, health issues, or
              damages arising from the use of AI-generated workout plans or nutrition advice. Use the
              Service at your own risk. The Service is provided &quot;as is&quot; without warranties of any
              kind.
            </p>
          </section>

          <section>
            <h2>9. Termination</h2>
            <p>
              We may terminate or suspend your account at any time for violation of these terms. Upon
              termination, your right to use the Service ceases immediately. You may export your data
              before account termination upon request.
            </p>
          </section>

          <section>
            <h2>10. Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. Material changes will be
              communicated via email or in-app notification. Continued use of the Service after
              changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2>11. Contact</h2>
            <p>
              For questions about these Terms, contact us at{' '}
              <a href="mailto:legal@vibecaas.com" className="text-blue-400 underline hover:text-blue-300">
                legal@vibecaas.com
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
