/** Daily macro targets */
export interface MacroTargets {
  calories: number;
  protein_g: number;
  carbs_g: number;
  fat_g: number;
}

/** Nutrition plan generated by AI */
export interface NutritionPlan {
  id: string;
  user_id: string;
  name: string;
  goal: string;
  daily_targets: MacroTargets;
  meals: MealTemplate[];
  is_ai_generated: boolean;
  created_at: string;
  updated_at: string;
}

/** Template for a meal within a nutrition plan */
export interface MealTemplate {
  name: string;
  time_of_day: string | null;
  foods: FoodItem[];
  macros: MacroTargets;
}

/** Individual food item */
export interface FoodItem {
  name: string;
  serving_size: string;
  macros: MacroTargets;
}

/** Logged meal entry */
export interface MealEntry {
  id: string;
  user_id: string;
  date: string;
  meal_name: string;
  foods: FoodItem[];
  total_macros: MacroTargets;
  created_at: string;
}
